### ISSUE TITLE
nothing happen with empty console log.. not work//

### ISSUE THREAD

**Issue by realsby** [timmyomahony/django-charsleft-widget#5]
Django (1.8.13)
django-suit (0.2.19)

statics loaded i can open from source code.. and modeladmin have..
formfield_overrides = {
    models.TextField: {'widget': CharsLeftInput()},
}

**Comment by timmyomahony** [comment]
Did you get this fixed?

**Comment by timmyomahony** [comment]
I'm closing this, let me know if you  (or anyone else) has encountered this issue
